### ISSUE TITLE
HTML output does not separate paragraphs

### ISSUE THREAD

**Issue by gogins** [csound-flossmanual/csound-floss#6]
In the HTML output for the manual, paragraphs that are separated by spaces in the markdown source are not separated by paragraphs in the compiled book.

In other words,
```
This is a nice markdown paragraph.

And after a blank line, this is another nice markdown paragraph.
```
becomes:
```
This is a nice markdown paragraph.
And after a blank line, this is another nice markdown paragraph.
```

**Comment by gogins** [comment]
I fixed this in my local repository by adding` margin-top: 12px;` to the paragraph style in the common.css file. The margins and/or padding of the lists could use a little work.

**Comment by hlolli** [comment]
Yes, that solution looks good to me, and I looked over your PR which looks good. I was just wondering about line breaks where a margin is unwanted. Should we make < br/> tags have margin 0 for that purpose? Otherwise, I would expect a normal markdown to compress any text source without an empty new-line to be inside one <p> tag and empty new-line seperating two <p> from one another.

**Comment by hlolli** [comment]
Sorry to be clear, two `<p>` should always have margin, so a 12px margin only makes sense. For the unwanted margin of line-break, I don't have a solution for atm.

**Comment by gogins** [comment]
Margin at top is removed by the layout engine sometimes, padding is never
removed.
