### ISSUE TITLE
releated with syntax

### ISSUE THREAD

**Issue by Demir-Fes** [csound-flossmanual/csound-floss#68]
Hello,

at this link
https://github.com/csound-flossmanual/csound-floss/blob/develop/book/03-a-initialization-and-performance-pass.md#init-versus-equals

I am not sure , I think there are some mistyped..."1 should be 0" and "perf. cycle should be control cycle".

releated sentence:
kCount = 1 sets the value for kCount to zero again and again, in each performance cycle.

**Comment by joachimheintz** [comment]
hi -

yes there was a typo.  it should be kCount=0 rather than kCount=1.

for the notion of performance versus control cycle, i am not sure.  i think we use the terms mostly for the same subject.  but i agree that control cycle is better here.  so i changed it, too.

thanks for your contribution!

  joachim
